"""add_cover_letter_title_unique_constraint

Revision ID: 63dc30afd0d1
Revises: 25eb30a4f4dd
Create Date: 2026-07-12 18:04:59.284728

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63dc30afd0d1"
down_revision: Union[str, Sequence[str], None] = "25eb30a4f4dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_cover_letter_resume_title"), "cover_letters", ["resume_id", "title"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_cover_letter_resume_title"),
        "cover_letters",
        type_="unique",
    )
    # ### end Alembic commands ###
