"""create_ai_usage_table

Revision ID: 6c7718072769
Revises: 63dc30afd0d1
Create Date: 2026-07-13 12:46:21.206998

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.database.enums import (
    ai_feature_enum,
    ai_request_status_enum,
)

# revision identifiers, used by Alembic.
revision: str = "6c7718072769"
down_revision: Union[str, Sequence[str], None] = "63dc30afd0d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        "ai_usage",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=True),
        sa.Column("cover_letter_id", sa.UUID(), nullable=True),
        sa.Column(
            "feature",
            ai_feature_enum,
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            ai_request_status_enum,
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letters.id"],
            name=op.f("fk_ai_usage_cover_letter_id_cover_letters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_ai_usage_resume_id_resumes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_usage_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index(
        "ix_ai_usage_status",
        "ai_usage",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_cover_letter_id"),
        "ai_usage",
        ["cover_letter_id"],
        unique=False,
    )
    op.create_index("ix_ai_usage_created_at", "ai_usage", ["created_at"], unique=False)
    op.create_index(op.f("ix_ai_usage_feature"), "ai_usage", ["feature"], unique=False)
    op.create_index(
        "ix_ai_usage_feature_created_at",
        "ai_usage",
        ["feature", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_resume_id"), "ai_usage", ["resume_id"], unique=False
    )
    op.create_index(
        "ix_ai_usage_user_created_at",
        "ai_usage",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_ai_usage_user_id"), "ai_usage", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_ai_usage_status",
        table_name="ai_usage",
    )
    op.drop_index(op.f("ix_ai_usage_user_id"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_user_created_at", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_resume_id"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_feature_created_at", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_feature"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_created_at", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_cover_letter_id"), table_name="ai_usage")
    op.drop_table("ai_usage")

    # ### end Alembic commands ###
