from app.common.constants import ResumeVersionSource
from app.resume_versions.repository import ResumeVersionRepository
from app.resume_versions.service import ResumeVersionService
from tests.factories.resume_factory import create_resume
from tests.factories.user_factory import create_user


def test_create_first_resume_version(
    db_session,
):
    user = create_user(db_session)

    resume = create_resume(
        db_session,
        user_id=user.id,
    )

    repository = ResumeVersionRepository(db_session)
    service = ResumeVersionService(repository)

    snapshot = {
        "title": "Backend Resume",
        "summary": "Python Backend Developer",
    }

    version = service.create_version(
        resume_id=resume.id,
        snapshot=snapshot,
        source=ResumeVersionSource.USER,
        change_summary="Initial resume version",
    )

    assert version.resume_id == resume.id
    assert version.version_number == 1
    assert version.snapshot == snapshot
    assert version.change_summary == "Initial resume version"
    assert version.source == "user"


def test_create_subsequent_resume_version_increments_version_number(
    db_session,
):
    user = create_user(db_session)

    resume = create_resume(
        db_session,
        user_id=user.id,
    )

    repository = ResumeVersionRepository(db_session)
    service = ResumeVersionService(repository)

    first_snapshot = {
        "title": "Backend Resume",
        "summary": "Python Developer",
    }

    second_snapshot = {
        "title": "Senior Backend Resume",
        "summary": "Senior Python Backend Developer",
    }

    first_version = service.create_version(
        resume_id=resume.id,
        snapshot=first_snapshot,
        source=ResumeVersionSource.USER,
    )

    second_version = service.create_version(
        resume_id=resume.id,
        snapshot=second_snapshot,
        source=ResumeVersionSource.USER,
        change_summary="Updated professional summary",
    )

    assert first_version.version_number == 1
    assert second_version.version_number == 2
    assert second_version.snapshot == second_snapshot
    assert second_version.change_summary == "Updated professional summary"


def test_create_version_supports_ai_source(
    db_session,
):
    user = create_user(db_session)

    resume = create_resume(
        db_session,
        user_id=user.id,
    )

    repository = ResumeVersionRepository(db_session)
    service = ResumeVersionService(repository)

    version = service.create_version(
        resume_id=resume.id,
        snapshot={
            "title": "AI Generated Resume",
        },
        source=ResumeVersionSource.AI,
        change_summary="Generated by AI",
    )

    assert version.version_number == 1
    assert version.source == ResumeVersionSource.AI.value


def test_create_version_supports_ats_source(
    db_session,
):
    user = create_user(db_session)

    resume = create_resume(
        db_session,
        user_id=user.id,
    )

    repository = ResumeVersionRepository(db_session)
    service = ResumeVersionService(repository)

    version = service.create_version(
        resume_id=resume.id,
        snapshot={
            "title": "ATS Optimized Resume",
        },
        source=ResumeVersionSource.ATS,
        change_summary="Optimized for ATS",
    )

    assert version.version_number == 1
    assert version.source == ResumeVersionSource.ATS.value


def test_create_version_allows_optional_change_summary(
    db_session,
):
    user = create_user(db_session)

    resume = create_resume(
        db_session,
        user_id=user.id,
    )

    repository = ResumeVersionRepository(db_session)
    service = ResumeVersionService(repository)

    version = service.create_version(
        resume_id=resume.id,
        snapshot={
            "title": "Backend Resume",
        },
        source=ResumeVersionSource.USER,
    )

    assert version.change_summary is None
